# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SV0e6BSKsdg1RY0pyPr-pBlp9WjM4PLT
"""

print("early weeds segmentation")

"""Data loading"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/INTERNSHIP/EARLY WEEDS SEGMENTATION/Crop_recommendation.csv")

df

df.head()

df.tail()

df.duplicated()

a=int(input("Enter the battery percentage"))
if a <=30 :
    print("Battery is full")
elif a <=70 :
     print("charge is enough")
else:
     print("need to charge")

a=(input())
if a=="red":
  print("stop")
elif a=="yellow":
  print("slow down")
else:
  print("go")

....a=int(input("Enter the value "))
for i in range(a):
  print(2*i+1, end=" ")

a=["bavi","nandhu"]
b=["123","456"]
a1=input("enter the username")
a2=input("enter the password")
if a1 in a:
  0
  index=a.index(a1)
  if a2==b[index]:
      print("login successfully ...")
  else:
      print("wrong password")
else:
  print("creat a new account")

a=int(input("enter the number"))
b=int(input("enter the number"))
c=int(input("enter the number"))
d=int(input("enter the number"))
e=int(input("enter the number"))

if a > b:
    a, b = b, a
if a > c:
    a, c = c, a
if a > d:
    a, d = d, a
if a > e:
    a, e = e, a

if b > c:
    b, c = c, b
if b > d:
    b, d = d, b
if b > e:
    b, e = e, b

if c > d:
    c, d = d, c
if c > e:
    c, e = e, c

if d > e:
    d, e = e, d

print(a,b,c,d,e)

